### ISSUE TITLE
Please don't parse whole URLs

### ISSUE THREAD

**Issue by stevenvachon** [peerigon/parse-domain#14]
Leave that complex process up to Node 7's `URL` and [whatwg-url](https://npmjs.com/whatwg-url).

This library is called "parse *domain*"

**Comment by jhnns** [comment]
Thanks for the feedback.

I know that "parsing" URLs with RegExp is brittle. I used this approach since I didn't want to force browserify/webpack users to include the whole url library. I thought that for the purpose of extracting the domain part using RegExp was sufficient. Can you give me an example where this approach doesn't work?

**Comment by jhnns** [comment]
With the next major version bump, we will just accept instances of the WHATWG `URL` constructor.

**Comment by jhnns** [comment]
Fixed with `v3.0.0` 🚀
