### ISSUE TITLE
Support for TypeScript on Node

### ISSUE THREAD

**Issue by DustinJSilk** [peerigon/parse-domain#145]
How can I get this library running with TypeScript and Node?

By default, I get ERR_REQUIRE_ESM errors.
If I add "type": "module" to my package.json it breaks my typescript configuration and all other imports.

Why doesn't this library support TS out of the box?

**Comment by thallada** [comment]
I believe this error is caused by: https://github.com/peerigon/parse-domain/issues/142

**Comment by jhnns** [comment]
`parse-domain` supports TypeScript out of the box. In fact, it is written in TypeScript. But since version 6.0.0 it's published as ECMAScript module only, see https://github.com/peerigon/parse-domain/issues/146#issuecomment-1171295159

If you're using TypeScript, you need to switch to `"module": "ES2020"` and add `"type": "module"` to your `package.json`. Here's a good blog post that explains how to do that: https://2ality.com/2021/06/typescript-esm-nodejs.html

**Comment by cmawhorter** [comment]
> If you're using TypeScript, you need to switch to "module": "ES2020" and add "type": "module" to your package.json

yikes, that's a pretty heavy requirement to throw at people with existing projects.  

it has been many months since the last time i gave esm a chance so i decided to read through the 2ality link and... holy crap.  nothing has changed.  

esm is a mess and i'm sure the tooling and everything will get there some day but it doesn't feel like that day is today.
