### ISSUE TITLE
wrong setting

### ISSUE THREAD

**Issue by bluelovers** [peerigon/parse-domain#146]
![image](https://user-images.githubusercontent.com/167966/167094032-37c52c43-4b44-4936-b193-3599887f27f9.png)

**Comment by jhnns** [comment]
Yes, since 6.0.0 the package is published as ECMAScript module only. Your options are:

- migrate your code to ECMAScript modules. It's the best long term solution but probably a lot of work. If you don't migrate, you will see this kind of error with every dependency update since more and more packages are migrating to ESM
- import it asynchronously via `await import("parse-domain")` (see https://nodejs.org/dist/latest-v16.x/docs/api/modules.html)
- stay on version 5.0.0

**Comment by bluelovers** [comment]
why not just push cjs and esm at same time?

**Comment by jhnns** [comment]
We already did it for two years, but cross-publishing ESM and CJS is not as easy as it sounds. There are a couple of pitfalls I don't want to care of any longer. A lot of module maintainers are slowly switching to ESM, so you probably won't have a choice in the long term.
If you're still using CJS, you can use version `5.0.0`. It already has the `parse-domain-update` command, so you can keep the internal list up-to-date.
