### ISSUE TITLE
Missing top level domains that got added past last publish date.

### ISSUE THREAD

**Issue by lukasholzer** [peerigon/parse-domain#152]
Can you release a new version of the package, or add the generation of the `serialized-tries/icann.js` to a `postinstall` script?

We need for example the new `.israel` top level domain that got added see: https://en.isoc.org.il/il-cctld/idn-domains-faq

Which is already registered in this list: https://publicsuffix.org/list/public_suffix_list.dat

**Comment by jhnns** [comment]
Hi @lukasholzer 👋 we used to do this on `postinstall` but there are lot of people who don't like scripts that request something from a remote origins on `postinstall`. For this reason I added `npx parse-domain-update` so that everyone can update the list when they need it (see https://github.com/peerigon/parse-domain#updates). Does that help? :)

**Comment by jhnns** [comment]
Closing this for now
