### ISSUE TITLE
Big bundle size

### ISSUE THREAD

**Issue by danieleleoni** [peerigon/parse-domain#19]
Hi guys,

my team and I already integrated your package into our multi-domain application and we are very happy with it, but recently we noticed that bundle size is increased a lot. Actually, parse-domain is the biggest package we have, even bigger than segment and moment, that are notoriously huge.

![screen shot 2017-07-21 at 12 21 59](https://user-images.githubusercontent.com/20039309/28459853-8b074b84-6e0f-11e7-8d7f-6bd77066262d.png)

I see there are a custom TLD option, that could be ok for use, but I guess if there are a solution to remove or prevent to include original objects and use only a custom file.

And, in any case, we can maybe reduce code here
https://github.com/peerigon/parse-domain/blob/master/lib/tld.js
since we can define a big set only once and not twice (once in the first row, once in the second)

Thanks guys and keep on working on this great package.
[the only one I see could recognise tld like .co.uk]

**Comment by jdolle** [comment]
Parse domain is also the largest package in my bundle. So much so that I am actively considering alternatives.

**Comment by jhnns** [comment]
Thanks for pointing out. I'm working on an [alternative trie representation of all tlds](https://github.com/peerigon/parse-domain/tree/refactor/improve-file-size). With that change, the list of icann TLDs is about 39kb parse size (compared to 210kb now), which roughly equals 18kb transfer size (gzipped). I'm afraid it won't get smaller than that since the list is awfully long 😁

**Comment by jhnns** [comment]
Parse size is now 63KB, gzipped and minified it's 30KB.

**Comment by jhnns** [comment]
I don't think that we can get a lot better than that, so closing it for now.
