### ISSUE TITLE
Error: Cannot find module '../build/tries/current/icann.complete.json'

### ISSUE THREAD

**Issue by MaximeArbisa** [peerigon/parse-domain#35]
Hello, everything is working well in local.
But when I try to clone and npm install my project, this error appears for parse-domain, in the line where I require it.

Do you know what may be the problem ?
In node_modules/parse-domain/build/tries when renaming folder pre/ to current/ it works, but what a quick fix ! And why is that folder absent locally ?

Locally:
NPM version: v5.6.0
Node.js version: v8.9.4 

Production:
NPM version: v3.8.9
Node.js version: v6.2.0

parse-domain: 2.1.1

Thank you ! :)

**Comment by iloughman** [comment]
Having this problem as well.

**Comment by unlight** [comment]
You broke all my CI builds
https://github.com/semantic-release/semantic-release/issues/816

**Comment by jhnns** [comment]
These issues arise during `postinstall` when something goes wrong [in this `catch` block](https://github.com/peerigon/parse-domain/blob/4c599bbc713150ef8e112478b799d2d055261d01/scripts/build-tries.js#L72-L88).

Since [`v2.1.0`](https://github.com/peerigon/parse-domain/releases/tag/v2.1.0) we're downloading the most up-to-date list from publicsuffix.org on `postinstall` (see [reasoning behind this change](https://github.com/peerigon/parse-domain/pull/36#issuecomment-396337122)). We try to compile the list and write it into the `build` folder in our module. If that goes wrong, we try to use a prebuilt list by copying the prebuilt one to the location where the compiled list is expected to be. If something goes wrong here, we can't recover from it.

Do you know why we can't write to the file system in your setup? Is there a better way to do it? Help appreciated ❤️.

**Comment by pvdlg** [comment]
Would it be possible to not write anything in the FS system in the fallback catch?
If the download of the list fails or if it cannot be written in the `build` directory, would it be possible to use a prebuilt list included in the module without having to copy it?
Maybe you could deliver the package with the prebuilt list in the `build` directory and try to download the updated list and overwrite the prebuilt one on `postinstall`. So if it fails the prebuilt list will be used automatically.

**Comment by jhnns** [comment]
Yes, I think that's possible. We could just overwrite the prebuilt list with the up-to-date list. In order to roll back if the unit test fails, we could read the file contents of the prebuilt list into memory before overwriting it with the new version. This way we can always fall back to the prebuilt list. File system access should work at that point because otherwise the updated list could not been overwritten in the first place.

Would you be up to a PR? I think the change shouldn't be too big:

-  Update [`build-tries`](https://github.com/peerigon/parse-domain/blob/master/scripts/build-tries.js)
- Remove [`write-pre`](https://github.com/peerigon/parse-domain/blob/master/scripts/write-pre.js)
- Update `package.json`

**Comment by sw-yx** [comment]
just noting **temporary fix: copy `node_modules/parse-domain/build/tries/pre` to `node_modules/parse-domain/build/tries/current`**

**Comment by pvdlg** [comment]
Unfortunately, I won't have time to make a PR.

**Comment by MaximeArbisa** [comment]
Hey guys, I've solved this issue by updating npm:

sudo npm install -g npm

Hope it will solve your problem too !
Cheers

**Comment by sw-yx** [comment]
well I was on npm 6.0.0 and had the issue - what did you upgrade from and to @MaximeArbisa ?

**Comment by MaximeArbisa** [comment]
@sw-yx, I was v3.8.9, now, I'm v6.1.0.
But locally, I'm v5.6.0, and have never had this problem ...

The problem only occured when I ran my code from development to production, where NPM version was 3.8.9, strange ...

**Comment by pvdlg** [comment]
@jhnns I opened the PR #39 as you suggested. Does the changes works for you?

**Comment by bodinsamuel** [comment]
Hi everyone,
this issue has some huge impact on big project. Is there any release date ? :)

**Comment by pvdlg** [comment]
@bodinsamuel as you experience this issue, could you try if my fix actually fix it?
Could you try to install the module from https://github.com/pvdlg/parse-domain/tree/overwrite-tries and see if that solve the problem?

`npm install pvdlg/parse-domain#overwrite-tries --save`

**Comment by revmischa** [comment]
I'm seeing this issue on latest parse-domain, building on travis CI

**Comment by pvdlg** [comment]
@jhnns, sorry to bother, but is there a change to get #39 merged? This is impacting a lot of people.

**Comment by aiankile** [comment]
Just as a side note: not npm-specific / having same issue _irregularly_ with yarn 1.7.0
