### ISSUE TITLE
Downloading public suffix list is is not deterministic. 

### ISSUE THREAD

**Issue by DrMiaow** [peerigon/parse-domain#42]
Is there to any way please to not have the module download public suffix lists at install time and instead have it default to something that could be maintained in a config file or part of the package?

As it stands this module results in non-deterministic builds. With the same version, the library can have different behaviours depending on the content of the downloaded files. 

Adding this feature would also help avoid issues such as https://github.com/peerigon/parse-domain/issues/35 in the future.

**Comment by jhnns** [comment]
I think you're right. I wouldn't worry about it being non-deterministic now because we're running the test suite after install against it. But doing these kind of things on `npm install` can be very brittle depending on your CI system.

I think we should provide an opt-in script for people that need an up-to-date list.

**Comment by silverwind** [comment]
The way I solve this in my modules is to have a weekly cronjob running that updates the module and then pushes a release if there are changes. Kind of scary to do this unattended, but so far it worked pretty good, see for example https://github.com/silverwind/oui.
