### ISSUE TITLE
Dependence on npm?

### ISSUE THREAD

**Issue by uncleramsay** [peerigon/parse-domain#52]
More of an FYI really. In version 2.1.5, you added a dependence on npm: https://github.com/peerigon/parse-domain/commit/d9d782b10afba2b8cb6784c2f2aee91f73192e6c - the build scripts now call `npm run`

My setup didn't have `npm` installed (I'm using `yarn` for package management), so this broke for me.

I realise that we're a long way off from removing dependence on `npm` altogether, so I've installed it for now, but I just thought you'd like to be aware that this may become more of an issue in the future.

**Comment by jhnns** [comment]
Thanks for the feedback 👍

I didn't know that people run `node` without having `npm` installed. But I'm fine with changing the `package.json` to be package manager agnostic. Since [`npm-run-all` runs commands via Yarn if Yarn is your package manager](https://github.com/mysticatea/npm-run-all#yarn-compatibility), you just need to replace all `npm run` calls with `run-s` in the `package.json`. Would you be up for pull request?

**Comment by jhnns** [comment]
Published with `v2.2.0` 🚀
