### ISSUE TITLE
Valid TLD Not Parsed

### ISSUE THREAD

**Issue by brendanw** [peerigon/parse-domain#82]
`parseDomain(""xn--90abvrccwbp.xn--p1acf")`

The above will return `null`.  `.xn--p1acf` is a valid TLD -> https://www.iana.org/domains/root/db/xn--p1acf.html

**Comment by sdgandhi** [comment]
You will have to convert from punycode back to utf since the tld list is in utf. @jhnns correct?

**Comment by jhnns** [comment]
Thanks for reporting this. Yes, with the current version, you will need to translate the Punycode to Unicode because the internal list of domain names is using Unicode.

However, this will change with the next major version bump (see #14). We will only accept sanitized hostnames (basically those from `new URL(url).hostname`).

**Comment by jhnns** [comment]
Fixed with `v3.0.0` 🚀
