### ISSUE TITLE
remove jest

### ISSUE THREAD

**Issue by SalvatorePreviti** [peerigon/parse-domain#93]
Remove JEST from package dependencies, it should be in devDependencies - is unsafe and dangerous to install jest and all its dependencies in a production server - this package cannot be used in production.

**Comment by jhnns** [comment]
https://github.com/peerigon/parse-domain/pull/91

Why is it unsafe? Do you have any sources about that?

**Comment by jhnns** [comment]
See also https://github.com/peerigon/parse-domain/issues/92#issuecomment-573457759

**Comment by esellin** [comment]
+1
I am using parse-domain in an AWS lambda, so I'm trying to keep things as lightweight as possible. Having jest as a dependency (rather than a devDependency) brings in tons of unnecessary crap, and is frankly insane.
If this 1-line fix isn't live very soon, I'll have to find an alternative solution to parse-domain.
